import { useDesktopLayout } from "@/features/shell/use-desktop-layout";
import { Alert } from "@/features/platform/alert";
import { Text } from "@/features/accessibility/app-text";
import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, View } from "react-native";
import { useFocusEffect, useLocalSearchParams, usePathname, useRouter } from "expo-router";
import { useAppearance } from "@/features/appearance/AppearanceProvider";
import { useLocalization } from "@/features/localization/LocalizationProvider";
import { adminDeleteHref } from "@/features/account/account-deletion";
import { ProfileAvatar } from "@/features/members/ProfileAvatar";
import { managementRepository } from "./management-repository";
import type { ManagedAccount, ManagementAction, ManagementState } from "./model";
import { managedAccountHref, resolveAccountId } from "./route-params";

const words = {
  en: { status: "Status", role: "Access role", linked: "Linked member", link: "Link member", create: "Create and link member", unlink: "Unlink member", unlinkDetail: "The account will return to waiting for approval. Ministries remain on the member record.", cancel: "Cancel", delete: "Delete account", error: "Unable to load this account.", invalid: "This account link is invalid.", missing: "This account is no longer available.", back: "Back to accounts", retry: "Try again", pending: "Pending", active: "Active", denied: "Denied", revoked: "Revoked", member: "Member", editor: "Editor", admin: "Administrator", notLinked: "Not linked" },
  uk: { status: "Статус", role: "Роль доступу", linked: "Пов’язаний учасник", link: "Пов’язати учасника", create: "Створити й пов’язати", unlink: "Від’єднати учасника", unlinkDetail: "Обліковий запис повернеться до очікування схвалення. Служіння залишаться в записі учасника.", cancel: "Скасувати", delete: "Видалити обліковий запис", error: "Не вдалося завантажити обліковий запис.", invalid: "Недійсне посилання на обліковий запис.", missing: "Цей обліковий запис більше недоступний.", back: "До облікових записів", retry: "Спробувати ще раз", pending: "Очікує", active: "Активний", denied: "Відхилений", revoked: "Відкликаний", member: "Учасник", editor: "Редактор", admin: "Адміністратор", notLinked: "Не пов’язано" },
} as const;
type LoadFailure = { kind: "invalid" | "missing" | "load"; message: string };

export function AccountDetailScreen() {
  const desktop = useDesktopLayout();
  const params = useLocalSearchParams<{ accountId?: string | string[] }>();
  const pathname = usePathname();
  const accountId = resolveAccountId(params.accountId, pathname);
  const router = useRouter() as any;
  const { palette } = useAppearance(); const { locale } = useLocalization(); const copy = words[locale];
  const [state, setState] = useState<ManagementState | null>(null); const [draft, setDraft] = useState<ManagedAccount | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [reload, setReload] = useState(0);
  useFocusEffect(useCallback(() => { let alive = true; setState(null); setDraft(null); setError(null); if (!accountId) { setError(copy.invalid); return; } void managementRepository.loadAccount(accountId).then((next) => { if (!alive) return; const account = next.accounts.find((item) => item.id === accountId); if (!account) setError(copy.missing); else { setState(next); setDraft(account); } }).catch((cause) => alive && setError(cause instanceof Error ? cause.message : copy.error)); return () => { alive = false; }; }, [accountId, copy.error, copy.invalid, copy.missing, reload]));
  if (!state || !draft) return <View style={[styles.center, { backgroundColor: palette.background }]}>{error ? <><Text selectable style={[styles.errorState, { color: palette.text }]}>{error}</Text><Pressable onPress={() => setReload((value) => value + 1)}><Text style={{ color: palette.accent, fontWeight: "800" }}>{copy.retry}</Text></Pressable><Pressable onPress={() => router.replace("/manage")}><Text style={{ color: palette.accent }}>{copy.back}</Text></Pressable></> : <ActivityIndicator color={palette.accent} />}</View>;
  const apply = async (action: ManagementAction) => { setBusy(true); setError(null); try { const next = await managementRepository.apply(state, action); setState(next); setDraft(next.accounts.find((item) => item.id === draft.id) ?? draft); } catch (cause) { setError(cause instanceof Error ? cause.message : copy.error); } finally { setBusy(false); } };
  const linked = draft.personId ? state.members.find((member) => member.id === draft.personId) : null;
  const option = (value: keyof typeof copy, current: string, action: ManagementAction) => <Pressable accessibilityRole="radio" accessibilityState={{ selected: current === value, disabled: busy }} disabled={busy} key={value} onPress={() => void apply(action)} style={[styles.option, { borderColor: current === value ? palette.accent : palette.line, backgroundColor: current === value ? palette.accentSoft : palette.surface }]}><Text style={{ color: palette.text, fontWeight: current === value ? "800" : "600" }}>{copy[value]}</Text></Pressable>;
  const unlink = () => Alert.alert(copy.unlink, copy.unlinkDetail, [{ text: copy.cancel, style: "cancel" }, { text: copy.unlink, style: "destructive", onPress: () => void apply({ type: "unlink-account", accountId: draft.id }) }]);
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={[styles.content, desktop && styles.desktopContent]} style={{ backgroundColor: palette.background }}>
    <View style={styles.identity}><ProfileAvatar backgroundColor={palette.accentSoft} name={linked?.name ?? draft.name} source={linked?.photo} size={56} textColor={palette.accent} /><View style={styles.flex}><Text style={[styles.title, { color: palette.text }]}>{linked?.name ?? draft.name}</Text><Text selectable style={{ color: palette.secondaryText }}>{draft.email || "—"}</Text></View></View>{error ? <Text accessibilityLiveRegion="polite" selectable style={{ color: palette.accent }}>{error}</Text> : null}
    <View style={[styles.columns, desktop && styles.desktopColumns]}><View style={[styles.column, desktop && styles.columnDesktop]}><Text style={[styles.section, { color: palette.text }]}>{copy.status}</Text><View style={styles.options}>{(["pending", "active", "denied", "revoked"] as const).map((value) => option(value, draft.status, { type: "set-account-status", accountId: draft.id, status: value }))}</View>
    <Text style={[styles.section, { color: palette.text }]}>{copy.role}</Text><View style={styles.options}>{(["member", "editor", "admin"] as const).map((value) => option(value, draft.role, { type: "set-account-role", accountId: draft.id, role: value }))}</View>
    </View><View style={[styles.column, desktop && styles.columnDesktop]}><View style={[styles.linkBox, { backgroundColor: palette.surface }]}><Text style={[styles.section, { color: palette.text }]}>{copy.linked}</Text><View style={styles.identity}><ProfileAvatar backgroundColor={palette.accentSoft} name={linked?.name ?? copy.notLinked} source={linked?.photo} size={38} textColor={palette.accent} /><Text style={{ color: palette.secondaryText }}>{linked?.name ?? copy.notLinked}</Text></View><Pressable disabled={busy} onPress={() => router.push(`/manage/account/${encodeURIComponent(draft.id)}/link`)} style={[styles.primary, { backgroundColor: palette.accent }]}><Text style={styles.primaryText}>{copy.link}</Text></Pressable><Pressable disabled={busy} onPress={() => router.push(`/manage/member/new?accountId=${encodeURIComponent(draft.id)}&returnTo=${encodeURIComponent(managedAccountHref(draft.id))}`)} style={styles.action}><Text style={{ color: palette.accent, fontWeight: "800" }}>{copy.create}</Text></Pressable>{linked ? <Pressable disabled={busy} onPress={unlink} style={styles.action}><Text style={{ color: palette.secondaryText }}>{copy.unlink}</Text></Pressable> : null}</View>
    <Pressable disabled={busy} onPress={() => router.push(adminDeleteHref(draft.id, linked?.name ?? draft.name))} style={styles.danger}><Text style={{ color: palette.accent, fontWeight: "800" }}>{copy.delete}</Text></Pressable>
    </View></View>
  </ScrollView>;
}

const styles = StyleSheet.create({ desktopContent: { padding: 32 }, columns: { gap: 12 }, desktopColumns: { flexDirection: "row", alignItems: "flex-start", gap: 32 }, columnDesktop: { flex: 1 }, column: { gap: 12, minWidth: 0 }, content: { flexGrow: 1, gap: 12, padding: 22, paddingBottom: 80 }, center: { alignItems: "center", flex: 1, gap: 18, justifyContent: "center", padding: 28 }, errorState: { fontSize: 19, fontWeight: "700", textAlign: "center" }, identity: { alignItems: "center", flexDirection: "row", gap: 12 }, flex: { flex: 1 }, title: { fontSize: 30, fontWeight: "800" }, section: { fontSize: 19, fontWeight: "800", marginTop: 18 }, options: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, option: { borderRadius: 12, borderWidth: 1, minWidth: "30%", paddingHorizontal: 14, paddingVertical: 12 }, linkBox: { borderRadius: 18, gap: 10, marginTop: 10, padding: 18 }, primary: { alignItems: "center", borderRadius: 12, marginTop: 6, padding: 14 }, primaryText: { color: "#FFF", fontWeight: "800" }, action: { alignItems: "center", justifyContent: "center", minHeight: 44 }, danger: { alignItems: "center", justifyContent: "center", marginTop: 18, minHeight: 48 } });
