import { useDesktopLayout } from "@/features/shell/use-desktop-layout";
import { Text, TextInput } from "@/features/accessibility/app-text";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, View } from "react-native";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useAppearance } from "@/features/appearance/AppearanceProvider";
import { useLocalization } from "@/features/localization/LocalizationProvider";
import { managementRepository } from "./management-repository";
import type { ManagedMinistry } from "./model";

export function MinistryFormScreen() {
  const desktop = useDesktopLayout();
  const { ministryId } = useLocalSearchParams<{ ministryId?: string }>(); const router = useRouter(); const { palette } = useAppearance(); const { locale } = useLocalization();
  const [item, setItem] = useState<ManagedMinistry | null>(null); const [name, setName] = useState(""); const [status, setStatus] = useState<"loading" | "ready" | "saving">(ministryId ? "loading" : "ready"); const [error, setError] = useState<string | null>(null);
  const labels = locale === "uk" ? { name: "Назва служіння", save: "Зберегти", archive: "Архівувати", restore: "Відновити", required: "Введіть назву служіння.", protected: "Це захищене служіння керує доступом до функцій застосунку й не може бути перейменоване або архівоване." } : { name: "Ministry name", save: "Save", archive: "Archive", restore: "Restore", required: "Enter a ministry name.", protected: "This protected ministry controls app capabilities and cannot be renamed or archived." };
  useEffect(() => { if (!ministryId) return; void managementRepository.listMinistries().then((all) => { const found = all.find((entry) => entry.id === ministryId) ?? null; setItem(found); setName(found?.name ?? ""); setStatus("ready"); }).catch((cause) => { setError(cause instanceof Error ? cause.message : labels.required); setStatus("ready"); }); }, [labels.required, ministryId]);
  async function save(archived = item?.archived ?? false) { if (!name.trim()) { setError(labels.required); return; } setStatus("saving"); setError(null); try { await managementRepository.saveMinistry({ id: item?.id, revision: item?.revision, name: name.trim(), archived }); (router.canGoBack() ? router.back() : router.replace("/manage/ministries")); } catch (cause) { setError(cause instanceof Error ? cause.message : labels.required); setStatus("ready"); } }
  if (status === "loading") return <View style={[styles.center, { backgroundColor: palette.background }]}><ActivityIndicator color={palette.accent} /></View>;
  return <ScrollView contentInsetAdjustmentBehavior="automatic" keyboardShouldPersistTaps="handled" contentContainerStyle={[styles.content, desktop && styles.desktopContent]} style={{ backgroundColor: palette.background }}><Text style={[styles.label, { color: palette.secondaryText }]}>{labels.name}</Text><TextInput autoFocus={!ministryId} editable={!item?.systemKey} value={name} onChangeText={setName} placeholder={labels.name} placeholderTextColor={palette.secondaryText} style={[styles.input, { backgroundColor: palette.surface, borderColor: palette.line, color: palette.text }, item?.systemKey && styles.protectedInput]} />{item?.systemKey ? <Text selectable style={{ color: palette.secondaryText }}>{labels.protected}</Text> : null}{error ? <Text accessibilityLiveRegion="polite" selectable style={{ color: palette.accent }}>{error}</Text> : null}{!item?.systemKey ? <Pressable disabled={status === "saving"} onPress={() => void save()} style={[styles.primary, { backgroundColor: palette.accent }]}>{status === "saving" ? <ActivityIndicator color="#FFF" /> : <Text style={styles.primaryText}>{labels.save}</Text>}</Pressable> : null}{item && !item.systemKey ? <Pressable disabled={status === "saving"} onPress={() => void save(!item.archived)} style={styles.archive}><Text style={{ color: palette.accent, fontWeight: "700" }}>{item.archived ? labels.restore : labels.archive}</Text></Pressable> : null}</ScrollView>;
}
const styles = StyleSheet.create({ desktopContent: { alignSelf: "center", width: "100%", maxWidth: 720, padding: 32 }, center: { alignItems: "center", flex: 1, justifyContent: "center" }, content: { gap: 12, padding: 18, paddingBottom: 48 }, label: { fontSize: 14, fontWeight: "600", marginTop: 8 }, input: { borderRadius: 14, borderWidth: StyleSheet.hairlineWidth, fontSize: 17, minHeight: 52, paddingHorizontal: 14 }, protectedInput: { opacity: 0.7 }, primary: { alignItems: "center", borderRadius: 14, justifyContent: "center", minHeight: 52, marginTop: 8 }, primaryText: { color: "#FFF", fontSize: 16, fontWeight: "800" }, archive: { alignItems: "center", justifyContent: "center", minHeight: 48, marginTop: 18 } });
