import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { useAppearance } from "@/features/appearance/AppearanceProvider";
import { useLocalization } from "@/features/localization/LocalizationProvider";
import { managementRepository } from "./management-repository";
import type { ManagedMinistry } from "./model";
export function MinistriesScreen() { const router = useRouter(); const { palette } = useAppearance(); const { locale } = useLocalization(); const [items, setItems] = useState<ManagedMinistry[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [error, setError] = useState<string | null>(null); const labels = locale === "uk" ? { title: "Служіння", add: "Додати", empty: "Немає служінь", archived: "Архівовано", retry: "Спробувати ще раз" } : { title: "Ministries", add: "Add", empty: "No ministries yet", archived: "Archived", retry: "Try again" }; const load = () => { setState("loading"); void managementRepository.listMinistries().then((next) => { setItems(next); setState("ready"); }).catch((e) => { setError(e instanceof Error ? e.message : labels.empty); setState("error"); }); }; useEffect(load, []); return <SafeAreaView style={[styles.safe, { backgroundColor: palette.background }]}><ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()}><Text style={[styles.action, { color: palette.accent }]}>‹</Text></Pressable><Text accessibilityRole="header" style={[styles.title, { color: palette.text }]}>{labels.title}</Text><Pressable accessibilityRole="button" onPress={() => router.push("/manage/ministry/new" as never)}><Text style={[styles.action, { color: palette.accent }]}>{labels.add}</Text></Pressable></View>{state === "loading" ? <ActivityIndicator color={palette.accent} /> : state === "error" ? <View style={styles.empty}><Text style={{ color: palette.secondaryText }}>{error}</Text><Pressable onPress={load}><Text style={[styles.action, { color: palette.accent }]}>{labels.retry}</Text></Pressable></View> : items.length ? items.map((item) => <Pressable accessibilityRole="button" key={item.id} onPress={() => router.push({ pathname: "/manage/ministry/[ministryId]", params: { ministryId: item.id } } as never)} style={[styles.row, { backgroundColor: palette.surface, borderColor: palette.line, opacity: item.archived ? 0.65 : 1 }]}><View style={styles.rowCopy}><Text style={[styles.name, { color: palette.text }]}>{locale === "uk" ? item.nameUk || item.name : item.name}</Text>{item.archived ? <Text style={[styles.detail, { color: palette.secondaryText }]}>{labels.archived}</Text> : item.nameUk && locale !== "uk" ? <Text style={[styles.detail, { color: palette.secondaryText }]}>{item.nameUk}</Text> : null}</View><Text style={[styles.chevron, { color: palette.secondaryText }]}>›</Text></Pressable>) : <Text style={[styles.empty, { color: palette.secondaryText }]}>{labels.empty}</Text>}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1 }, content: { gap: 12, padding: 18, paddingBottom: 48 }, header: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", paddingBottom: 12 }, title: { fontSize: 22, fontWeight: "800" }, action: { fontSize: 17, fontWeight: "700" }, row: { alignItems: "center", borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, flexDirection: "row", minHeight: 68, padding: 16 }, rowCopy: { flex: 1, gap: 4 }, name: { fontSize: 17, fontWeight: "700" }, detail: { fontSize: 14 }, chevron: { fontSize: 28 }, empty: { alignItems: "center", gap: 12, padding: 30, textAlign: "center" } });
