import { useCallback, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useFocusEffect, useRouter } from "expo-router";
import { useAppearance } from "@/features/appearance/AppearanceProvider";
import { useLocalization } from "@/features/localization/LocalizationProvider";
import { managementRepository } from "./management-repository";
import type { ManagedMinistry } from "./model";

export function MinistriesScreen() {
  const router = useRouter(); const { palette } = useAppearance(); const { locale } = useLocalization(); const [items, setItems] = useState<ManagedMinistry[]>([]); const [state, setState] = useState<"loading" | "ready" | "error">("loading"); const [error, setError] = useState<string | null>(null);
  const labels = locale === "uk" ? { add: "Додати служіння", empty: "Служінь ще немає", archived: "Архівовано", retry: "Спробувати ще раз" } : { add: "Add ministry", empty: "No ministries yet", archived: "Archived", retry: "Try again" };
  const load = useCallback(() => { setState("loading"); void managementRepository.listMinistries().then((next) => { setItems(next); setState("ready"); }).catch((cause) => { setError(cause instanceof Error ? cause.message : labels.empty); setState("error"); }); }, [labels.empty]);
  useFocusEffect(load);
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.content} style={{ backgroundColor: palette.background }}><Pressable accessibilityRole="button" onPress={() => router.push("/manage/ministry/new" as never)} style={[styles.add, { borderColor: palette.accent }]}><Text style={{ color: palette.accent, fontWeight: "800" }}>+ {labels.add}</Text></Pressable>{state === "loading" ? <ActivityIndicator color={palette.accent} /> : state === "error" ? <View style={styles.empty}><Text selectable style={{ color: palette.secondaryText }}>{error}</Text><Pressable onPress={load}><Text style={{ color: palette.accent, fontWeight: "700" }}>{labels.retry}</Text></Pressable></View> : items.length ? <View style={[styles.list, { backgroundColor: palette.surface, borderColor: palette.line }]}>{items.map((item, index) => <Pressable accessibilityRole="button" key={item.id} onPress={() => router.push({ pathname: "/manage/ministry/[ministryId]", params: { ministryId: item.id } } as never)} style={[styles.row, index < items.length - 1 && { borderBottomColor: palette.line, borderBottomWidth: StyleSheet.hairlineWidth }, item.archived && styles.archived]}><View style={{ flex: 1 }}><Text style={[styles.name, { color: palette.text }]}>{item.name}</Text>{item.archived ? <Text style={{ color: palette.secondaryText }}>{labels.archived}</Text> : null}</View><Text style={[styles.chevron, { color: palette.secondaryText }]}>›</Text></Pressable>)}</View> : <Text style={[styles.empty, { color: palette.secondaryText }]}>{labels.empty}</Text>}</ScrollView>;
}
const styles = StyleSheet.create({ content: { gap: 14, padding: 18, paddingBottom: 48 }, add: { alignItems: "center", borderRadius: 14, borderWidth: 1, justifyContent: "center", minHeight: 48 }, list: { borderCurve: "continuous", borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, overflow: "hidden" }, row: { alignItems: "center", flexDirection: "row", minHeight: 62, paddingHorizontal: 16, paddingVertical: 10 }, name: { fontSize: 17, fontWeight: "700" }, chevron: { fontSize: 28 }, archived: { opacity: 0.58 }, empty: { alignItems: "center", gap: 12, padding: 30, textAlign: "center" } });
