import { Ionicons } from "@react-native-vector-icons/ionicons";
import { Image } from "expo-image";
import { type Href, useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Linking, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";

import { useAppearance } from "@/features/appearance/AppearanceProvider";
import { useLocalization } from "@/features/localization/LocalizationProvider";
import { useSession } from "@/features/session/SessionProvider";
import { getMemberCopy } from "./member-copy";
import { memberProfileRepository, type MemberProfile } from "./member-repository";
import { CareStatusBadges } from "./care-status-badges";

export function MemberProfileScreen({ memberId }: { memberId: string }) {
  const router = useRouter(); const { palette } = useAppearance(); const session = useSession(); const insets = useSafeAreaInsets();
  const { locale } = useLocalization(); const copy = getMemberCopy(locale);
  const [profile, setProfile] = useState<MemberProfile | null | undefined>(); const [failed, setFailed] = useState(false);
  const load = () => { setProfile(undefined); setFailed(false); memberProfileRepository.getProfile(memberId).then(setProfile).catch(() => { setFailed(true); setProfile(null); }); };
  useEffect(load, [memberId]);
  const open = async (url: string) => { try { if (await Linking.canOpenURL(url)) await Linking.openURL(url); } catch { /* Native service unavailable. */ } };
  if (profile === undefined) return <ProfileState loading title={copy.loading} />;
  if (!profile || failed) return <ProfileState action={failed ? load : undefined} detail={failed ? undefined : copy.unavailableDetail} title={failed ? copy.error : copy.unavailable} />;

  const name = locale === "uk" ? profile.nameUk : profile.name; const group = locale === "uk" ? profile.membershipGroupUk : profile.membershipGroup; const responsibilityGroup = locale === "uk" ? profile.responsibilityGroupUk : profile.responsibilityGroup; const ministries = locale === "uk" ? profile.ministriesUk : profile.ministries;
  const age = profile.birthDate ? Math.floor((Date.now() - new Date(`${profile.birthDate}T12:00:00`).getTime()) / 31557600000) : null;
  const formatDate = (value: string) => new Intl.DateTimeFormat(locale === "uk" ? "uk-UA" : "en-US", { dateStyle: "long", timeZone: "UTC" }).format(new Date(`${value}T12:00:00Z`));
  // Email is an operational contact reserved for church leadership. Use the
  // profile's ministry designation, rather than the viewer's role, so a
  // deacon/pastor profile remains reachable by authorized directory users.
  const isLeadership = profile.designation === "deacon" || profile.designation === "pastor";
  const isWidow = ["widow", "widowed", "вдова", "вдівець", "вдівець/вдова"].includes(profile.maritalStatus?.trim().toLocaleLowerCase() ?? "");
  const canRequestVisit = session.status === "ready" && session.account.designation === "pastor";

  return <View style={[styles.root, { backgroundColor: palette.background }]}><ScrollView contentInsetAdjustmentBehavior="never" contentContainerStyle={styles.screen} keyboardShouldPersistTaps="handled">
    <View style={[styles.hero, { paddingTop: insets.top }]}><Image accessibilityLabel={`${name} ${copy.profile}`} contentFit="cover" source={profile.photo} style={StyleSheet.absoluteFill} /><View style={styles.heroShade} />
      <Pressable accessibilityLabel={copy.back} onPress={() => router.back()} style={[styles.floatingButton, { top: insets.top + 12 }]}><Ionicons color="#FFF" name="chevron-back" size={24} /></Pressable>
      <View style={styles.heroCopy}><Text accessibilityRole="header" style={styles.name}>{name}</Text>{profile.designation !== "none" ? <View style={{ alignSelf: "flex-start", backgroundColor: "rgba(13,18,22,0.7)", borderRadius: 8, marginTop: 8, paddingHorizontal: 9, paddingVertical: 4 }}><Text style={{ color: "#FFF", fontSize: 13, fontWeight: "800" }}>{profile.designation === "pastor" ? "Pastor" : "Deacon"}</Text></View> : null}<View style={styles.ministryRow}>{ministries.map((ministry, index) => <Text key={`${profile.id}:hero-ministry:${index}`} style={styles.heroPillText}>{ministry}</Text>)}</View><CareStatusBadges isOrphan={profile.isOrphan} isWidow={isWidow} /></View>
    </View>
    <View style={styles.body}>
      {canRequestVisit ? <Pressable onPress={() => router.push({ pathname: "/visitation/new", params: { person: memberId } } as Href)} style={({ pressed }) => [styles.visitButton, { backgroundColor: palette.accent }, pressed && styles.pressed]}><Ionicons color="#FFF" name="calendar-outline" size={21} /><Text style={styles.visitButtonText}>{copy.requestVisit}</Text></Pressable> : null}
      <Section title={copy.contact}><View style={styles.actions}>{profile.phone ? <Action icon="call-outline" label={copy.call} onPress={() => void open(`tel:${profile.phone!.replace(/[^+\d]/g, "")}`)} /> : null}{isLeadership && profile.email ? <Action icon="mail-outline" label={copy.email} onPress={() => void open(`mailto:${profile.email}`)} /> : null}{profile.address ? <Action icon="map-outline" label={copy.maps} onPress={() => void open(`https://maps.apple.com/?q=${encodeURIComponent(profile.address!)}`)} /> : null}</View>{profile.phone ? <Text selectable style={[styles.phone, { color: palette.text }]}>{profile.phone}</Text> : null}{profile.address ? <Text style={[styles.address, { color: palette.secondaryText }]}>{profile.address}</Text> : null}</Section>
      <Section title={copy.details}>{profile.birthDate ? <Fact label={copy.birthday} value={formatDate(profile.birthDate)} /> : null}{age !== null ? <Fact label={copy.age} value={String(age)} /> : null}{profile.membershipJoinedAt ? <Fact label={copy.memberSince} value={formatDate(profile.membershipJoinedAt)} /> : null}{profile.maritalStatus ? <Fact label={copy.maritalStatus} value={profile.maritalStatus} /> : null}{profile.membershipGroupId ? <Pressable accessibilityHint={copy.openGroup} accessibilityLabel={`${copy.group}: ${group || "—"}`} accessibilityRole="button" onPress={() => router.push(`/groups/${profile.membershipGroupId}` as never)} style={({ pressed }) => pressed && styles.pressedRow}><Fact disclosure label={copy.group} last={!profile.responsibilityGroupId} value={group || "—"} /></Pressable> : <Fact label={copy.group} last={!profile.responsibilityGroupId} value={group || "—"} />}{profile.responsibilityGroupId ? <Pressable accessibilityHint={copy.openGroup} accessibilityLabel={`${copy.responsibleFor}: ${responsibilityGroup || "—"}`} accessibilityRole="button" onPress={() => router.push(`/groups/${profile.responsibilityGroupId}` as never)} style={({ pressed }) => pressed && styles.pressedRow}><Fact disclosure label={copy.responsibleFor} last value={responsibilityGroup || "—"} /></Pressable> : null}</Section>
      <Section title={copy.ministries}><View style={styles.bodyList}>{ministries.map((ministry, index) => <Text key={`${profile.id}:detail-ministry:${index}`} style={[styles.bodyListText, { color: palette.text }]}>{ministry}</Text>)}</View></Section>
    </View>
  </ScrollView></View>;
}

function Action({ icon, label, onPress }: { icon: "call-outline" | "mail-outline" | "map-outline"; label: string; onPress: () => void }) { const { palette } = useAppearance(); return <Pressable accessibilityRole="button" onPress={onPress} style={[styles.action, { backgroundColor: palette.accentSoft }]}><Ionicons color={palette.accent} name={icon} size={23} /><Text style={[styles.actionText, { color: palette.accent }]}>{label}</Text></Pressable>; }
function Section({ children, title }: { children: React.ReactNode; title: string }) { const { palette } = useAppearance(); return <View style={styles.section}><Text accessibilityRole="header" style={[styles.sectionTitle, { color: palette.text }]}>{title}</Text><View style={[styles.card, { backgroundColor: palette.surface, borderColor: palette.line }]}>{children}</View></View>; }
function Fact({ disclosure = false, label, value, last = false }: { disclosure?: boolean; label: string; value: string; last?: boolean }) { const { palette } = useAppearance(); return <View style={[styles.fact, !last && { borderBottomColor: palette.line, borderBottomWidth: StyleSheet.hairlineWidth }]}><Text style={[styles.factLabel, { color: palette.secondaryText }]}>{label}</Text><View style={styles.factValueRow}><Text selectable style={[styles.factValue, { color: disclosure ? palette.accent : palette.text }]}>{value}</Text>{disclosure ? <Ionicons accessibilityElementsHidden color={palette.accent} name="chevron-forward" size={18} /> : null}</View></View>; }
function ProfileState({ action, detail, loading, title }: { action?: () => void; detail?: string; loading?: boolean; title: string }) { const { palette } = useAppearance(); const { locale } = useLocalization(); const copy = getMemberCopy(locale); return <View style={[styles.state, { backgroundColor: palette.background }]}>{loading ? <ActivityIndicator color={palette.accent} /> : <Ionicons color={palette.secondaryText} name="person-outline" size={30} />}<Text style={[styles.stateTitle, { color: palette.text }]}>{title}</Text>{detail ? <Text style={[styles.stateDetail, { color: palette.secondaryText }]}>{detail}</Text> : null}{action ? <Pressable onPress={action} style={{ alignItems: "center", backgroundColor: palette.accent, borderRadius: 11, paddingHorizontal: 15, paddingVertical: 11 }}><Text style={{ color: "#FFF", fontWeight: "800" }}>{copy.retry}</Text></Pressable> : null}</View>; }

const styles = StyleSheet.create({ root: { flex: 1 }, screen: { paddingBottom: 112 }, hero: { backgroundColor: "#36414A", height: 390, overflow: "hidden", position: "relative" }, heroShade: { backgroundColor: "rgba(5,10,14,0.25)", bottom: 0, left: 0, position: "absolute", right: 0, top: 0 }, floatingButton: { alignItems: "center", backgroundColor: "rgba(10,14,18,0.55)", borderRadius: 22, height: 44, justifyContent: "center", left: 16, position: "absolute", width: 44 }, heroCopy: { bottom: 24, left: 20, position: "absolute", right: 20 }, name: { color: "#FFF", fontSize: 38, fontWeight: "800", letterSpacing: -1, lineHeight: 43, textShadowColor: "rgba(0,0,0,0.35)", textShadowRadius: 8 }, ministryRow: { flexDirection: "row", flexWrap: "wrap", gap: 7, marginTop: 10 }, heroPill: { backgroundColor: "rgba(13,18,22,0.7)", borderRadius: 8, paddingHorizontal: 9, paddingVertical: 4 }, heroPillText: { color: "#FFF", fontSize: 13, fontWeight: "700" }, body: { gap: 18, padding: 18 }, visitButton: { alignItems: "center", borderRadius: 14, flexDirection: "row", gap: 9, justifyContent: "center", minHeight: 52 }, visitButtonText: { color: "#FFF", fontSize: 16, fontWeight: "800" }, section: { gap: 8 }, sectionTitle: { fontSize: 19, fontWeight: "800" }, card: { borderCurve: "continuous", borderRadius: 16, borderWidth: StyleSheet.hairlineWidth, overflow: "hidden" }, actions: { flexDirection: "row", gap: 9, padding: 12 }, action: { alignItems: "center", borderRadius: 12, flex: 1, gap: 5, justifyContent: "center", minHeight: 62 }, actionText: { fontSize: 13, fontWeight: "800" }, phone: { fontSize: 16, fontWeight: "700", paddingHorizontal: 14, paddingBottom: 5 }, address: { fontSize: 14, lineHeight: 20, paddingBottom: 14, paddingHorizontal: 14 }, fact: { alignItems: "center", flexDirection: "row", gap: 14, justifyContent: "space-between", minHeight: 52, paddingHorizontal: 14, paddingVertical: 10 }, factLabel: { fontSize: 14 }, factValueRow: { alignItems: "center", flex: 1, flexDirection: "row", gap: 7, justifyContent: "flex-end" }, factValue: { flexShrink: 1, fontSize: 15, fontWeight: "600", textAlign: "right" }, pressedRow: { opacity: .65 }, bodyList: { gap: 8, padding: 14 }, bodyListText: { fontSize: 15, fontWeight: "600" }, pressed: { opacity: 0.75, transform: [{ scale: 0.99 }] }, state: { alignItems: "center", flex: 1, gap: 10, justifyContent: "center", padding: 30 }, stateTitle: { fontSize: 18, fontWeight: "700", textAlign: "center" }, stateDetail: { textAlign: "center" } });
