import type { AppLocale } from "@/features/localization/LocalizationProvider";

const en = {
    title: "Visitation",
    current: "Current",
    archive: "Archive",
    planVisit: "Plan visit",
    editVisit: "Edit planned visit",
    invitations: "Invitations",
    myVisits: "My planned visits",
    previewIdentity: "Preview identity",
    previewHint: "Local fixture mode",
    plannedBy: "Planned by",
    plannedByMe: "Planned by me",
    person: "Person to visit",
    choosePerson: "Choose a person",
    noResults: "No matches found.",
    date: "Date",
    time: "Time",
    location: "Visit location",
    phone: "Phone number",
    notes: "Visit notes",
    optional: "Optional",
    participants: "Participants",
    organizer: "Organizer",
    chooseParticipants:
        "Optional. Invite pastors or deacons; you are already included as the planner.",
    noParticipants: "No other pastor or deacon members are available.",
    noAccount: "No account",
    plannerOnly: "No additional participants. The planner is attending.",
    pastor: "Pastor",
    deacon: "Deacon",
    groupDeacon: "Responsibility group",
    save: "Save changes",
    saving: "Saving…",
    create: "Plan visit",
    loading: "Loading visits…",
    loadingMore: "Loading more visits…",
    loadMore: "Load more visits",
    loadingDetail: "Loading visit…",
    retry: "Try again",
    emptyCurrent: "No current planned visits.",
    emptyCurrentDetail: "New invitations and planned visits will appear here.",
    emptyArchive: "No archived visits.",
    emptyArchiveDetail: "Visits archived by their planner will appear here.",
    notFound: "This visit is unavailable.",
    notFoundDetail:
        "It may have been removed, or you may no longer be a participant.",
    refresh: "Refresh",
    pending: "Pending",
    accepted: "Accepted",
    declined: "Declined",
    open: "Planned",
    completed: "Completed",
    cancelled: "Cancelled",
    archived: "Archived",
    updated: "Updated details",
    updatedDetail:
        "The planner changed this visit. Review the latest details before responding.",
    yourResponse: "Your response",
    accept: "Accept",
    decline: "Decline",
    declineReason: "Decline reason (optional)",
    responseSaved: "Response saved.",
    manage: "Manage visit",
    edit: "Edit",
    complete: "Mark completed",
    cancel: "Cancel planned visit",
    archiveVisit: "Archive visit",
    confirmComplete:
        "Mark this visit completed? It will remain in Current until you archive it.",
    confirmCancel:
        "Cancel this planned visit? It will remain in Current until you archive it.",
    confirmArchive: "Move this completed or cancelled visit to the archive?",
    confirmAction: "Confirm",
    keepVisit: "Go back",
    noNotes: "No notes",
    noReason: "No reason provided",
    openMaps: "Open visit location in Maps",
    validationPerson: "Choose a person to visit.",
    validationDate: "Enter a valid date in YYYY-MM-DD format.",
    validationTime: "Enter a valid time in HH:mm format.",
    validationLocation: "Enter the visit location.",
    conflictTitle: "This visit changed",
    conflictDetail:
        "Your draft is still here. Refresh the latest visit, review it, and save again.",
    loadFailed: "Unable to load visits.",
    saveFailed: "Unable to save. Your draft has been retained.",
    forbidden: "This action is not available for your account.",
    viewDetails: "View visit details",
    back: "Back",
    notificationNote:
        "Lock-screen notifications contain no names, times, locations, or notes.",
    addCalendar: "Add to calendar",
    calendarSnapshot: "Create calendar snapshot?",
    calendarSnapshotDetail:
        "Your calendar will open with a copy of the current date, time, person, and location. Later visit changes will not update that calendar event.",
    openCalendar: "Open calendar",
    calendarFailed: "Unable to open the calendar. Try again.",
} as const;

const uk: Record<keyof typeof en, string> = {
    title: "Відвідування",
    current: "Поточні",
    archive: "Архів",
    planVisit: "Запланувати відвідування",
    editVisit: "Змінити заплановане відвідування",
    invitations: "Запрошення",
    myVisits: "Мої заплановані відвідування",
    previewIdentity: "Перегляд від імені",
    previewHint: "Локальний демонстраційний режим",
    plannedBy: "Запланував",
    plannedByMe: "Заплановано мною",
    person: "Кого відвідати",
    choosePerson: "Оберіть людину",
    noResults: "Збігів не знайдено.",
    date: "Дата",
    time: "Час",
    location: "Місце відвідування",
    phone: "Номер телефону",
    notes: "Примітки до відвідування",
    optional: "Необов’язково",
    participants: "Учасники",
    organizer: "Організатор",
    chooseParticipants:
        "Необов’язково. Запросіть пасторів або дияконів; ви вже берете участь як організатор.",
    noParticipants: "Немає інших членів-пасторів або дияконів.",
    noAccount: "Без облікового запису",
    plannerOnly: "Додаткових учасників немає. Організатор бере участь.",
    pastor: "Пастор",
    deacon: "Диякон",
    groupDeacon: "Група відповідальності",
    save: "Зберегти зміни",
    saving: "Збереження…",
    create: "Запланувати відвідування",
    loading: "Завантаження відвідувань…",
    loadingMore: "Завантаження наступних відвідувань…",
    loadMore: "Завантажити ще відвідувань",
    loadingDetail: "Завантаження відвідування…",
    retry: "Спробувати ще раз",
    emptyCurrent: "Поточних запланованих відвідувань немає.",
    emptyCurrentDetail:
        "Нові запрошення та заплановані відвідування з’являться тут.",
    emptyArchive: "Архів відвідувань порожній.",
    emptyArchiveDetail: "Архівовані організатором відвідування з’являться тут.",
    notFound: "Це відвідування недоступне.",
    notFoundDetail: "Його могли видалити, або ви більше не є учасником.",
    refresh: "Оновити",
    pending: "Очікується",
    accepted: "Прийнято",
    declined: "Відхилено",
    open: "Заплановано",
    completed: "Завершено",
    cancelled: "Скасовано",
    archived: "В архіві",
    updated: "Деталі оновлено",
    updatedDetail:
        "Організатор змінив це відвідування. Перегляньте актуальні деталі перед відповіддю.",
    yourResponse: "Ваша відповідь",
    accept: "Прийняти",
    decline: "Відхилити",
    declineReason: "Причина відмови (необов’язково)",
    responseSaved: "Відповідь збережено.",
    manage: "Керування відвідуванням",
    edit: "Редагувати",
    complete: "Позначити завершеним",
    cancel: "Скасувати відвідування",
    archiveVisit: "Архівувати відвідування",
    confirmComplete:
        "Позначити це відвідування завершеним? Воно залишиться в поточних, доки ви його не архівуєте.",
    confirmCancel:
        "Скасувати це відвідування? Воно залишиться в поточних, доки ви його не архівуєте.",
    confirmArchive:
        "Перемістити це завершене або скасоване відвідування до архіву?",
    confirmAction: "Підтвердити",
    keepVisit: "Повернутися",
    noNotes: "Приміток немає",
    noReason: "Причину не вказано",
    openMaps: "Відкрити місце відвідування в Картах",
    validationPerson: "Оберіть людину для відвідування.",
    validationDate: "Введіть коректну дату у форматі РРРР-ММ-ДД.",
    validationTime: "Введіть коректний час у форматі ГГ:ХХ.",
    validationLocation: "Введіть місце відвідування.",
    conflictTitle: "Це відвідування змінилося",
    conflictDetail:
        "Вашу чернетку збережено. Оновіть відвідування, перегляньте деталі та збережіть знову.",
    loadFailed: "Не вдалося завантажити відвідування.",
    saveFailed: "Не вдалося зберегти. Вашу чернетку збережено.",
    forbidden: "Ця дія недоступна для вашого облікового запису.",
    viewDetails: "Переглянути деталі відвідування",
    back: "Назад",
    notificationNote:
        "Сповіщення на екрані блокування не містять імен, часу, місця чи приміток.",
    addCalendar: "Додати до календаря",
    calendarSnapshot: "Створити копію в календарі?",
    calendarSnapshotDetail:
        "Календар відкриється з копією поточних дати, часу, імені та місця. Подальші зміни відвідування не оновлять цю подію календаря.",
    openCalendar: "Відкрити календар",
    calendarFailed: "Не вдалося відкрити календар. Спробуйте ще раз.",
};

export const visitationCopy = (locale: AppLocale) =>
    locale === "uk" ? uk : en;
export type VisitationCopy = ReturnType<typeof visitationCopy>;
