import type { VisitActor, VisitParticipant, VisitPerson, VisitRecord } from "./types";

export const visitationActors: VisitActor[] = [
  { id: "pastor-olena", personId: "olena-kovalenko", displayName: "Olena Account", leadershipMinistry: "pastor", role: "member", status: "active", revision: 1 },
  { id: "pastor-mykola", personId: "mykola-petrenko", displayName: "Mykola Account", leadershipMinistry: "pastor", role: "member", status: "active", revision: 1 },
  { id: "deacon-marko", personId: "marko-melnyk", displayName: "Marko Account", leadershipMinistry: "deacon", role: "member", status: "active", revision: 1 },
  { id: "deacon-leah", personId: "leah-thompson", displayName: "Leah Account", leadershipMinistry: "deacon", role: "editor", status: "active", revision: 1 },
];

export const visitationPeople: VisitPerson[] = [
  {
    id: "marta-kovalenko",
    name: "Marta Kovalenko",
    phone: "+1 (916) 555-0138",
    address: "2480 Fair Oaks Boulevard, Sacramento, CA",
    responsibilityGroupId: "responsibility-east",
  },
  {
    id: "daniel-brooks",
    name: "Daniel Brooks",
    phone: "+1 (916) 555-0182",
    address: "1017 48th Street, Sacramento, CA",
    responsibilityGroupId: "responsibility-central",
  },
  {
    id: "amelia-carter",
    name: "Amelia Carter",
    phone: null,
    address: "3900 J Street, Sacramento, CA",
    responsibilityGroupId: null,
  },
];

export const visitationParticipants: VisitParticipant[] = [
  { accountId: "pastor-olena", personId: "olena-kovalenko", name: "Olena Kovalenko", leadershipMinistry: "pastor", responsibilityGroupId: null },
  { accountId: "pastor-mykola", personId: "mykola-petrenko", name: "Mykola Petrenko", leadershipMinistry: "pastor", responsibilityGroupId: null },
  { accountId: "deacon-marko", personId: "marko-melnyk", name: "Marko Melnyk", leadershipMinistry: "deacon", responsibilityGroupId: "responsibility-east" },
  { accountId: "deacon-leah", personId: "leah-thompson", name: "Leah Thompson", leadershipMinistry: "deacon", responsibilityGroupId: "responsibility-central" },
  { accountId: null, personId: "deacon-no-account", name: "No Account Deacon", leadershipMinistry: "deacon", responsibilityGroupId: "responsibility-east" },
];

export const visitationVisits: VisitRecord[] = [
  {
    id: "visit-marta",
    plannerId: "pastor-olena",
    personId: "marta-kovalenko",
    plannerName: "Olena Kovalenko",
    memberName: "Marta Kovalenko",
    memberPhone: "+1 (916) 555-0138",
    scheduledAt: "2027-01-16T01:30:00.000Z",
    location: "2480 Fair Oaks Boulevard, Sacramento, CA",
    notes: "Meet at the front entrance.",
    status: "open",
    archivedAt: null,
    completedAt: null,
    revision: 2,
    submissionId: "fixture-marta",
    updatedFields: ["location"],
    recipients: [
      {
        accountId: "deacon-marko",
        participantName: "Marko Melnyk",
        participantPersonId: "marko-melnyk",
        leadershipMinistry: "deacon",
        response: "pending",
        reason: null,
        lastViewedRevision: 1,
      },
      {
        accountId: "deacon-leah",
        participantName: "Leah Thompson",
        participantPersonId: "leah-thompson",
        leadershipMinistry: "deacon",
        response: "accepted",
        reason: null,
        lastViewedRevision: 2,
      },
    ],
  },
  {
    id: "visit-daniel",
    plannerId: "pastor-olena",
    personId: "daniel-brooks",
    plannerName: "Olena Kovalenko",
    memberName: "Daniel Brooks",
    memberPhone: "+1 (916) 555-0182",
    scheduledAt: "2026-09-13T22:00:00.000Z",
    location: "Mercy General Hospital, main lobby",
    notes: "",
    status: "completed",
    archivedAt: null,
    completedAt: "2026-09-13T23:20:00.000Z",
    revision: 3,
    submissionId: "fixture-daniel",
    updatedFields: [],
    recipients: [
      {
        accountId: "deacon-marko",
        participantName: "Marko Melnyk",
        participantPersonId: "marko-melnyk",
        leadershipMinistry: "deacon",
        response: "accepted",
        reason: null,
        lastViewedRevision: 3,
      },
    ],
  },
  {
    id: "visit-amelia",
    plannerId: "pastor-olena",
    personId: "amelia-carter",
    plannerName: "Olena Kovalenko",
    memberName: "Amelia Carter",
    memberPhone: null,
    scheduledAt: "2026-09-08T17:00:00.000Z",
    location: "3900 J Street, Sacramento, CA",
    notes: "Reschedule when the family is available.",
    status: "cancelled",
    archivedAt: "2026-09-09T17:00:00.000Z",
    completedAt: null,
    revision: 3,
    submissionId: "fixture-amelia",
    updatedFields: [],
    recipients: [
      {
        accountId: "deacon-marko",
        participantName: "Marko Melnyk",
        participantPersonId: "marko-melnyk",
        leadershipMinistry: "deacon",
        response: "declined",
        reason: "Already committed to another visit.",
        lastViewedRevision: 2,
      },
    ],
  },
];
